version: '3.9'

services:
  localstack:
    build: .
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
    environment:
      - LAMBDA_EXECUTOR=local
