apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: apps
type: Opaque
stringData:
  awsAccessKeyID: test
  awsSecretAccessKey: test
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: aws-trigger-auth
  namespace: apps
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: aws-creds
      key: awsAccessKeyID
    - parameter: awsSecretAccessKey
      name: aws-creds
      key: awsSecretAccessKey
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-consumer-fila-1-scaler
  namespace: apps
spec:
  scaleTargetRef:
    name: demo-consumer-fila-1
  minReplicaCount: 0
  maxReplicaCount: 5
  pollingInterval: 30
  cooldownPeriod: 30
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: http://localstack.apps.svc.cluster.local:4566/000000000000/generic-queue-real-time
        queueLength: "100"
        awsRegion: us-east-1
        awsEndpoint: http://localstack.apps.svc.cluster.local:4566
      authenticationRef:
        name: aws-trigger-auth
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-consumer-fila-2-scaler
  namespace: apps
spec:
  scaleTargetRef:
    name: demo-consumer-fila-2
  minReplicaCount: 0
  maxReplicaCount: 5
  pollingInterval: 30
  cooldownPeriod: 30
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: http://localstack.apps.svc.cluster.local:4566/000000000000/generic-queue-lazy-time
        queueLength: "100"
        awsRegion: us-east-1
        awsEndpoint: http://localstack.apps.svc.cluster.local:4566
      authenticationRef:
        name: aws-trigger-auth
