spring:
  application:
    name: demo-consumer

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

logging:
  level:
    root: INFO

aws:
  region: ${AWS_REGION}
  endpoint: ${AWS_ENDPOINT}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  sqs:
    queue-url-1: ${AWS_SQS_QUEUE_URL_1}
    consumer-1-enabled: ${SQS_CONSUMER_1_ENABLED}
    consumer-1-parallel: ${SQS_CONSUMER_1_PARALLEL}
    consumer-1-threads: ${SQS_CONSUMER_1_THREADS}
    consumer-1-delay: ${SQS_CONSUMER_1_DELAY}
    queue-url-2: ${AWS_SQS_QUEUE_URL_2}
    consumer-2-enabled: ${SQS_CONSUMER_2_ENABLED}
    consumer-2-parallel: ${SQS_CONSUMER_2_PARALLEL}
    consumer-2-threads: ${SQS_CONSUMER_2_THREADS}
    consumer-2-delay: ${SQS_CONSUMER_2_DELAY}
