version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-consumer
    network_mode: host
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/elastic-apm-agent.jar
      - ELASTIC_APM_SERVICE_NAME=demo-consumer
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_APPLICATION_PACKAGES=com.example.demo.consumer.config

      # Server
      - SERVER_PORT=9090
      - SERVER_CONTEXT_PATH=/demo-consumer/v1

      # AWS config
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT=http://localhost:4566
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_KEY=test

      # SQS Queues
      - AWS_SQS_QUEUE_URL_1=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/generic-queue-real-time
      - AWS_SQS_QUEUE_URL_2=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/generic-queue-lazy-time

      # SQS Workers (Consumer 1)
      - SQS_CONSUMER_1_ENABLED=true
      - SQS_CONSUMER_1_PARALLEL=false
      - SQS_CONSUMER_1_THREADS=5

      # SQS Workers (Consumer 2)
      - SQS_CONSUMER_2_ENABLED=true
      - SQS_CONSUMER_2_PARALLEL=false
      - SQS_CONSUMER_2_THREADS=5
